---
Name: shortcodable
After:
    - framework/*
---

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'violet88/silverstripe-shortcodable: javascript/shortcodable.js'
  extra_requirements_css:
    - 'violet88/silverstripe-shortcodable: css/shortcodable.css'

SilverStripe\Control\Director:
  rules:
    "_shortcodable//$Action": 'Violet88\Shortcodable\Controllers\ShortcodableController'

Violet88\Shortcodable\Shortcodable:
  htmleditor_names:
    - cms
