---
Name: shortcodable
After:
    - framework/*
    # - cms/*
---

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'violet88/silverstripe-shortcodable: javascript/shortcodable.js'
  extra_requirements_css:
    - 'violet88/silverstripe-shortcodable: css/shortcodable.css'

SilverStripe\Control\Director:
  rules:
    "_shortcodable//$Action": 'Silverstripe\Shortcodable\Controller\ShortcodableController'

Silverstripe\Shortcodable:
  htmleditor_names:
    - cms
